FROM phpmyadmin/phpmyadmin

# Optional: Add custom configurations, themes, or plugins
# COPY ./config.inc.php /etc/phpmyadmin/config.inc.php
# COPY ./themes /usr/share/phpmyadmin/themes
# COPY ./plugins /usr/share/phpmyadmin/plugins

# Example of adding a custom configuration
# ENV PMA_HOST your_database_host
# ENV PMA_USER your_database_user
# ENV PMA_PASSWORD your_database_password
# ENV PMA_PORT your_database_port
